name: book_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/naruto_vol_01.jpg
    - assets/image/solo_leveling.jpg
    - assets/image/the_untamed.jpg
    - assets/image/profile.jpg
